// @lytjs/shared-types - 统一类型导出

export type { RefLike } from './ref';
export type { BaseAppConfig, BaseAppContext, Plugin } from './app-context';
export type { Props } from './vnode';
export type { ReactiveEffectRef, DebuggerEvent } from './debug';
export type { Renderer, Directive, DirectiveBinding, DirectiveArguments } from './renderer';
export type {
  SlotFunction,
  InternalSlots,
  ComponentPublicInstance,
  ComponentInternalInstance,
  ComponentOptionsBase,
} from './component';
// Web 相关类型
export type {
  HttpMethod,
  Metadata,
  OpenGraphMetadata,
  TwitterMetadata,
  HttpContext,
  HttpRequest,
  HttpResponse,
  HttpRoute,
} from './web';
// 类型工具
export type {
  Prettify,
  PartialExcept,
  RequiredExcept,
  Mutable,
  DeepMutable,
  DeepReadonly,
  ExtractKeysByType,
  OmitByType,
  PickByType,
  Maybe,
  MaybeArray,
  Nullable,
  Optional,
  Without,
  FunctionKeys,
  NonFunctionKeys,
  Constructor,
  AbstractConstructor,
  ValueOf,
  PromiseOrValue,
  AsyncFunction,
  AnyFunction,
  EmptyObject,
  Dictionary,
  NumericDictionary,
  Primitive,
  Nullish,
  NonNullish,
  ArrayElement,
  Last,
  First,
  TupleToUnion,
  UnionToIntersection,
  IsAny,
  IsNever,
  IsUnknown,
  IfAny,
  IfNever,
  IfUnknown,
  Awaited,
  Equal,
  Expect,
  Not,
  And,
  Or,
  Extends,
  Override,
  Merge,
  StrictMerge,
  DeepPartial,
  DeepRequired,
  DeepPick,
  MarkNonNullable,
  MarkNullable,
  MarkOptional,
  MarkRequired,
  StringKeyOf,
  NumberKeyOf,
  SymbolKeyOf,
  WritableKeys,
  ReadonlyKeys,
  RequiredKeys,
  OptionalKeys,
  PickRequired,
  PickOptional,
  OmitRequired,
  OmitOptional,
  // v6.8.0 新增：更好的泛型推断类型工具
  Parameters,
  ReturnType,
  ConstructorParameters,
  InstanceType,
  UnwrapPromise,
  DeepFlatten,
  NonOptionalProperties,
  Combine,
  StrictCombine,
  // v6.8.0 新增：类型守卫增强
  TypeGuard,
  UnionTypeGuard,
  TypeGuardFactory,
  NullableTypeGuard,
  ArrayTypeGuard,
  // v6.8.0 新增：模板字符串类型支持
  Join,
  Split,
  CamelToSnake,
  SnakeToCamel,
  CamelToKebab,
  KebabToCamel,
  // v6.8.0 新增：类型安全的事件系统类型
  EventHandler,
  EventListeners,
  IEventEmitter,
  DefineEvents,
  ExtendEvents,
  // v6.8.0 新增：更强大的类型推断工具
  KeyOf,
  ElementOf,
  PromiseResult,
  ThisParameterType,
  OmitThisParameter,
} from './type-utils';

// v6.8.0 新增：类型安全的事件发射器实现
export { EventEmitter, createEventEmitter } from './event-emitter';

// v6.8.0 新增：类型守卫运行时工具
export {
  isString,
  isNumber,
  isBoolean,
  isObject,
  isArray,
  isFunction,
  isNull,
  isUndefined,
  isNullish,
  hasProperty,
  createArrayTypeGuard,
  createObjectTypeGuard,
} from './type-utils';
