# 赞助 Lyt.js

感谢你对 Lyt.js 的支持！如果你觉得这个项目对你有帮助，可以考虑赞助我们。

# 这些是占位符配置，请根据实际情况修改

github: [lytjs]
# patreon: lytjs
# open_collective: lytjs
# ko_fi: lytjs
# tidelift: npm/lytjs
# community_bridge: lytjs
# liberapay: lytjs
# issuehunt: lytjs
# otechie: lytjs
# lfx_crowdfunding: lytjs
# custom: ['https://gitee.com/lytjs']
