export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "common",
        "reactivity",
        "vdom",
        "compiler",
        "renderer",
        "component",
        "core",
        "ecosystem",
        "lytui",
        "plugins",
        "tools",
        "docs",
        "ci",
        "release",
      ],
    ],
    "scope-case": [2, "always", "lower-case"],
    "subject-max-length": [2, "always", 72],
  },
};
