packages:
  # 子仓库（孙仓库级）
  - 'packages/common/packages/*'
  - 'packages/ecosystem/packages/*'
  - 'packages/plugins/packages/*'
  - 'packages/tools/packages/*'

  # 子仓库（单包级）
  - 'packages/shared-types'
  - 'packages/host-contract'
  - 'packages/reactivity'
  - 'packages/dom-runtime'
  - 'packages/vdom'
  - 'packages/compiler'
  - 'packages/renderer'
  - 'packages/adapter-web'
  - 'packages/component'
  - 'packages/core'
  - 'packages/core-vnode'
  - 'packages/core-signal'
  - 'packages/dom'
  - 'packages/web'

  # 根仓库应用
  - 'docs'
  - 'examples/*'
  - 'benchmarks/*'
  - 'e2e/*'
  - 'playground'
allowBuilds:
  esbuild: set this to true or false
  vue-demi: set this to true or false
onlyBuiltDependencies:
  - esbuild
