// src/sfc/typescript.ts
// TypeScript type declaration generation from SFC descriptors

import type { SFCDescriptor } from './parse';

// ============================================================
// Types
// ============================================================

export interface ComponentTypeInfo {
  name: string;
  props: PropDeclaration[];
  emits: EmitDeclaration[];
  exposed: string[];
  slots: string[];
}

export interface PropDeclaration {
  name: string;
  type: string;
  required: boolean;
  default?: string;
}

export interface EmitDeclaration {
  name: string;
  payload?: string;
}

// ============================================================
// Regex patterns for extracting component information
// ============================================================

// Match defineComponent<...>( or defineComponent(
// FIX: P2-26 使用花括号计数替代简单的 <[^>]*>，支持嵌套泛型如 defineComponent<Props<T>>(
const RE_DEFINE_COMPONENT_START = /defineComponent\s*(?:<)?\s*\(\s*\{/;

// Match props: { ... } - we'll use brace-counting for extraction
const RE_PROPS_START = /props\s*:\s*\{/;

// Match emits: [...] or emits: { ... }
const RE_EMITS_ARRAY = /emits\s*:\s*\[([^\]]*)\]/;
const RE_EMITS_OBJECT_START = /emits\s*:\s*\{/;

// Match individual prop declarations: propName: { type: ..., required: ... }
const RE_PROP_DECLARATION =
  /(\w+)\s*:\s*\{[^}]*type\s*:\s*(\w+)[^}]*required\s*:\s*(true|false)[^}]*/g;

// Match simple prop declarations: propName: Type
const RE_PROP_SIMPLE = /(\w+)\s*:\s*(String|Number|Boolean|Array|Object|Function|Symbol)/g;

// Match export default { ... }
const RE_EXPORT_DEFAULT_START = /export\s+default\s+\{/;

// Match component name
const RE_COMPONENT_NAME = /name\s*:\s*['"](\w+)['"]/;

// ============================================================
// generateComponentTypes
// ============================================================

/**
 * Generate TypeScript type declarations (.d.ts content) from an SFC descriptor.
 *
 * This is a simplified implementation that uses regex-based extraction.
 * A production version would use a proper TypeScript AST parser.
 *
 * @param descriptor - The parsed SFC descriptor
 * @returns Generated .d.ts file content as a string
 */
export function generateComponentTypes(descriptor: SFCDescriptor): string {
  const info = extractComponentInfo(descriptor);
  const lines: string[] = [];

  // File header
  const componentName = info.name || toPascalCase(stripExtension(descriptor.filename));
  lines.push(`// Type declarations for ${componentName}`);
  lines.push(`// Auto-generated by @lytjs/compiler`);
  lines.push('');

  // Import statement for the base component type
  lines.push(`import type { Component } from '@lytjs/renderer';`);
  lines.push('');

  // Generate props interface
  if (info.props.length > 0) {
    lines.push(`export interface ${componentName}Props {`);
    for (const prop of info.props) {
      const optional = prop.required ? '' : '?';
      const defaultSuffix = prop.default !== undefined ? ` // default: ${prop.default}` : '';
      lines.push(`  readonly ${prop.name}${optional}: ${prop.type};${defaultSuffix}`);
    }
    lines.push('}');
    lines.push('');
  }

  // Generate emits type
  if (info.emits.length > 0) {
    lines.push(`export interface ${componentName}Emits {`);
    for (const emit of info.emits) {
      const eventHandler = `on${capitalize(emit.name)}: `;
      if (emit.payload) {
        lines.push(`  ${eventHandler}(payload: ${emit.payload}): void;`);
      } else {
        lines.push(`  ${eventHandler}(): void;`);
      }
    }
    lines.push('}');
    lines.push('');
  }

  // Generate component instance type
  const propsType = info.props.length > 0 ? `${componentName}Props` : '{}';
  const emitsType = info.emits.length > 0 ? `, ${componentName}Emits` : '';
  lines.push(`export type ${componentName}Instance = InstanceType<Component<${propsType}${emitsType}>>;`);
  lines.push('');

  // Default export declaration
  lines.push(`declare const _default: Component<${propsType}${emitsType}>;`);
  lines.push(`export default _default;`);
  lines.push('');

  return lines.join('\n');
}

// ============================================================
// Component Info Extraction
// ============================================================

/**
 * Extract component type information from the SFC descriptor's script blocks.
 */
function extractComponentInfo(descriptor: SFCDescriptor): ComponentTypeInfo {
  const scriptContent =
    descriptor.script?.content ?? descriptor.scriptSetup?.content ?? '';

  const info: ComponentTypeInfo = {
    name: '',
    props: [],
    emits: [],
    exposed: [],
    slots: [],
  };

  if (!scriptContent.trim()) {
    return info;
  }

  // Extract component name
  const nameMatch = scriptContent.match(RE_COMPONENT_NAME);
  if (nameMatch) {
    info.name = nameMatch[1]!;
  }

  // Try to extract from defineComponent first
  const dcStartMatch = scriptContent.match(RE_DEFINE_COMPONENT_START);
  if (dcStartMatch) {
    const dcBody = extractBracedContent(scriptContent, dcStartMatch.index! + dcStartMatch[0]!.length - 1);
    if (dcBody) {
      extractPropsFromObject(dcBody, info);
      extractEmitsFromObject(dcBody, info);
    }
  } else {
    // Fall back to export default { ... }
    const edStartMatch = scriptContent.match(RE_EXPORT_DEFAULT_START);
    if (edStartMatch) {
      const exportBody = extractBracedContent(scriptContent, edStartMatch.index! + edStartMatch[0]!.length - 1);
      if (exportBody) {
        extractPropsFromObject(exportBody, info);
        extractEmitsFromObject(exportBody, info);
      }
    }
  }

  return info;
}

/**
 * Extract content enclosed in braces starting at the given position.
 * Uses brace-counting to handle nested objects correctly.
 *
 * @param source - The full source string
 * @param openBraceIndex - The index of the opening '{'
 * @returns The content between the outermost braces (excluding the braces), or null
 */
function extractBracedContent(source: string, openBraceIndex: number): string | null {
  if (source[openBraceIndex] !== '{') return null;

  let depth = 0;
  let inString: string | null = null;
  let escaped = false;

  for (let i = openBraceIndex; i < source.length; i++) {
    const char = source[i]!;

    if (escaped) {
      escaped = false;
      continue;
    }

    if (char === '\\') {
      escaped = true;
      continue;
    }

    if (inString) {
      if (char === inString) {
        inString = null;
      }
      continue;
    }

    if (char === '"' || char === "'" || char === '`') {
      inString = char;
      continue;
    }

    if (char === '{') {
      depth++;
    } else if (char === '}') {
      depth--;
      if (depth === 0) {
        return source.slice(openBraceIndex + 1, i);
      }
    }
  }

  return null;
}

/**
 * Extract props declarations from an object literal string.
 */
function extractPropsFromObject(
  body: string,
  info: ComponentTypeInfo,
): void {
  const propsStartMatch = body.match(RE_PROPS_START);
  if (!propsStartMatch) {
    return;
  }

  const propsBody = extractBracedContent(body, propsStartMatch.index! + propsStartMatch[0]!.length - 1);
  if (!propsBody) return;

  // Try detailed prop declarations first: propName: { type: X, required: Y }
  let match: RegExpExecArray | null;
  RE_PROP_DECLARATION.lastIndex = 0;
  while ((match = RE_PROP_DECLARATION.exec(propsBody)) !== null) {
    const name = match[1]!;
    const rawType = match[2]!;
    const required = match[3] === 'true';
    info.props.push({
      name,
      type: mapPropType(rawType),
      required,
    });
  }

  // If no detailed declarations found, try simple ones: propName: Type
  if (info.props.length === 0) {
    RE_PROP_SIMPLE.lastIndex = 0;
    while ((match = RE_PROP_SIMPLE.exec(propsBody)) !== null) {
      const name = match[1]!;
      const rawType = match[2]!;
      info.props.push({
        name,
        type: mapPropType(rawType),
        required: false,
      });
    }
  }
}

/**
 * Extract emits declarations from an object literal string.
 */
function extractEmitsFromObject(
  body: string,
  info: ComponentTypeInfo,
): void {
  // Try array form: emits: ['event1', 'event2']
  const arrayMatch = body.match(RE_EMITS_ARRAY);
  if (arrayMatch) {
    const events = arrayMatch[1]!;
    const eventNames = events.match(/['"](\w+)['"]/g);
    if (eventNames) {
      for (const event of eventNames) {
        const name = event.replace(/['"]/g, '');
        info.emits.push({ name });
      }
    }
    return;
  }

  // Try object form: emits: { event1: (payload: Type) => true }
  const objectStartMatch = body.match(RE_EMITS_OBJECT_START);
  if (objectStartMatch) {
    const emitsBody = extractBracedContent(body, objectStartMatch.index! + objectStartMatch[0]!.length - 1);
    if (emitsBody) {
      const eventNames = emitsBody.match(/(\w+)\s*:/g);
      if (eventNames) {
        for (const event of eventNames) {
          const name = event.replace(/[\s:]/g, '');
          info.emits.push({ name });
        }
      }
    }
    return;
  }
}

// ============================================================
// Type Mapping Utilities
// ============================================================

/**
 * Map Vue-style prop type constructors to TypeScript types.
 */
function mapPropType(rawType: string): string {
  const typeMap: Record<string, string> = {
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Array: 'unknown[]',
    Object: 'Record<string, unknown>',
    Function: '(...args: unknown[]) => unknown',
    Symbol: 'symbol',
  };
  return typeMap[rawType] ?? rawType;
}

/**
 * Capitalize the first letter of a string.
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Convert a kebab-case or snake_case filename to PascalCase.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((part) => capitalize(part))
    .join('');
}

/**
 * Strip the file extension from a filename.
 */
function stripExtension(filename: string): string {
  const lastDot = filename.lastIndexOf('.');
  return lastDot > 0 ? filename.slice(0, lastDot) : filename;
}
