// src/sfc/typescript.ts
// 从 SFC 描述符生成 TypeScript 类型声明

import type { SFCDescriptor } from './parse';

// ============================================================
// 类型定义
// ============================================================

export interface ComponentTypeInfo {
  name: string;
  props: PropDeclaration[];
  emits: EmitDeclaration[];
  exposed: string[];
  slots: string[];
}

export interface PropDeclaration {
  name: string;
  type: string;
  required: boolean;
  default?: string;
}

export interface EmitDeclaration {
  name: string;
  payload?: string;
}

// ============================================================
// 用于提取组件信息的正则表达式模式
// ============================================================

// 匹配 defineComponent<...>( 或 defineComponent(
// FIX: P2-26 使用花括号计数替代简单的 <[^>]*>，支持嵌套泛型如 defineComponent<Props<T>>(
const RE_DEFINE_COMPONENT_START = /defineComponent\s*(?:<)?\s*\(\s*\{/;

// 匹配 props: { ... } - 我们将使用大括号计数进行提取
const RE_PROPS_START = /props\s*:\s*\{/;

// 匹配 emits: [...] 或 emits: { ... }
const RE_EMITS_ARRAY = /emits\s*:\s*\[([^\]]*)\]/;
const RE_EMITS_OBJECT_START = /emits\s*:\s*\{/;

// 匹配单个 prop 声明：propName: { type: ..., required: ... }
const RE_PROP_DECLARATION =
  /(\w+)\s*:\s*\{[^}]*type\s*:\s*(\w+)[^}]*required\s*:\s*(true|false)[^}]*/g;

// 匹配简单 prop 声明：propName: Type
const RE_PROP_SIMPLE = /(\w+)\s*:\s*(String|Number|Boolean|Array|Object|Function|Symbol)/g;

// 匹配 export default { ... }
const RE_EXPORT_DEFAULT_START = /export\s+default\s+\{/;

// 匹配组件名称
const RE_COMPONENT_NAME = /name\s*:\s*['"](\w+)['"]/;

// ============================================================
// generateComponentTypes
// ============================================================

/**
 * 从 SFC 描述符生成 TypeScript 类型声明（.d.ts 内容）。
 *
 * 这是一个使用基于正则表达式提取的简化实现。
 * A production version would use a proper TypeScript AST parser.
 *
 * @param descriptor - The parsed SFC descriptor
 * @returns Generated .d.ts file content as a string
 */
export function generateComponentTypes(descriptor: SFCDescriptor): string {
  const info = extractComponentInfo(descriptor);
  const lines: string[] = [];

  // 文件头
  const componentName = info.name || toPascalCase(stripExtension(descriptor.filename));
  lines.push(`// Type declarations for ${componentName}`);
  lines.push(`// Auto-generated by @lytjs/compiler`);
  lines.push('');

  // 基础组件类型的导入语句
  lines.push(`import type { Component } from '@lytjs/renderer';`);
  lines.push('');

  // 生成 props 接口
  if (info.props.length > 0) {
    lines.push(`export interface ${componentName}Props {`);
    for (const prop of info.props) {
      const optional = prop.required ? '' : '?';
      const defaultSuffix = prop.default !== undefined ? ` // default: ${prop.default}` : '';
      lines.push(`  readonly ${prop.name}${optional}: ${prop.type};${defaultSuffix}`);
    }
    lines.push('}');
    lines.push('');
  }

  // 生成 emits 类型
  if (info.emits.length > 0) {
    lines.push(`export interface ${componentName}Emits {`);
    for (const emit of info.emits) {
      const eventHandler = `on${capitalize(emit.name)}: `;
      if (emit.payload) {
        lines.push(`  ${eventHandler}(payload: ${emit.payload}): void;`);
      } else {
        lines.push(`  ${eventHandler}(): void;`);
      }
    }
    lines.push('}');
    lines.push('');
  }

  // 生成组件实例类型
  const propsType = info.props.length > 0 ? `${componentName}Props` : '{}';
  const emitsType = info.emits.length > 0 ? `, ${componentName}Emits` : '';
  lines.push(
    `export type ${componentName}Instance = InstanceType<Component<${propsType}${emitsType}>>;`,
  );
  lines.push('');

  // 默认导出声明
  lines.push(`declare const _default: Component<${propsType}${emitsType}>;`);
  lines.push(`export default _default;`);
  lines.push('');

  return lines.join('\n');
}

// ============================================================
// 组件信息提取
// ============================================================

/**
 * 从 SFC 描述符的 script 块中提取组件类型信息。
 */
function extractComponentInfo(descriptor: SFCDescriptor): ComponentTypeInfo {
  const scriptContent = descriptor.script?.content ?? descriptor.scriptSetup?.content ?? '';

  const info: ComponentTypeInfo = {
    name: '',
    props: [],
    emits: [],
    exposed: [],
    slots: [],
  };

  if (!scriptContent.trim()) {
    return info;
  }

  // 提取组件名称
  const nameMatch = scriptContent.match(RE_COMPONENT_NAME);
  if (nameMatch) {
    info.name = nameMatch[1]!;
  }

  // 首先尝试从 defineComponent 提取
  const dcStartMatch = scriptContent.match(RE_DEFINE_COMPONENT_START);
  if (dcStartMatch) {
    const dcBody = extractBracedContent(
      scriptContent,
      dcStartMatch.index! + dcStartMatch[0]!.length - 1,
    );
    if (dcBody) {
      extractPropsFromObject(dcBody, info);
      extractEmitsFromObject(dcBody, info);
    }
  } else {
    // 回退到 export default { ... }
    const edStartMatch = scriptContent.match(RE_EXPORT_DEFAULT_START);
    if (edStartMatch) {
      const exportBody = extractBracedContent(
        scriptContent,
        edStartMatch.index! + edStartMatch[0]!.length - 1,
      );
      if (exportBody) {
        extractPropsFromObject(exportBody, info);
        extractEmitsFromObject(exportBody, info);
      }
    }
  }

  return info;
}

/**
 * 从给定位置提取大括号内包含的内容。
 * 使用大括号计数正确处理嵌套对象。
 *
 * @param source - The full source string
 * @param openBraceIndex - The index of the opening '{'
 * @returns The content between the outermost braces (excluding the braces), or null
 */
function extractBracedContent(source: string, openBraceIndex: number): string | null {
  if (source[openBraceIndex] !== '{') return null;

  let depth = 0;
  let inString: string | null = null;
  let escaped = false;

  for (let i = openBraceIndex; i < source.length; i++) {
    const char = source[i]!;

    if (escaped) {
      escaped = false;
      continue;
    }

    if (char === '\\') {
      escaped = true;
      continue;
    }

    if (inString) {
      if (char === inString) {
        inString = null;
      }
      continue;
    }

    if (char === '"' || char === "'" || char === '`') {
      inString = char;
      continue;
    }

    if (char === '{') {
      depth++;
    } else if (char === '}') {
      depth--;
      if (depth === 0) {
        return source.slice(openBraceIndex + 1, i);
      }
    }
  }

  return null;
}

/**
 * 从对象字面量字符串中提取 props 声明。
 */
function extractPropsFromObject(body: string, info: ComponentTypeInfo): void {
  const propsStartMatch = body.match(RE_PROPS_START);
  if (!propsStartMatch) {
    return;
  }

  const propsBody = extractBracedContent(
    body,
    propsStartMatch.index! + propsStartMatch[0]!.length - 1,
  );
  if (!propsBody) return;

  // 首先尝试详细 prop 声明：propName: { type: X, required: Y }
  let match: RegExpExecArray | null;
  RE_PROP_DECLARATION.lastIndex = 0;
  while ((match = RE_PROP_DECLARATION.exec(propsBody)) !== null) {
    const name = match[1]!;
    const rawType = match[2]!;
    const required = match[3] === 'true';
    info.props.push({
      name,
      type: mapPropType(rawType),
      required,
    });
  }

  // 如果未找到详细声明，尝试简单的：propName: Type
  if (info.props.length === 0) {
    RE_PROP_SIMPLE.lastIndex = 0;
    while ((match = RE_PROP_SIMPLE.exec(propsBody)) !== null) {
      const name = match[1]!;
      const rawType = match[2]!;
      info.props.push({
        name,
        type: mapPropType(rawType),
        required: false,
      });
    }
  }
}

/**
 * 从对象字面量字符串中提取 emits 声明。
 */
function extractEmitsFromObject(body: string, info: ComponentTypeInfo): void {
  // 尝试数组形式：emits: ['event1', 'event2']
  const arrayMatch = body.match(RE_EMITS_ARRAY);
  if (arrayMatch) {
    const events = arrayMatch[1]!;
    const eventNames = events.match(/['"](\w+)['"]/g);
    if (eventNames) {
      for (const event of eventNames) {
        const name = event.replace(/['"]/g, '');
        info.emits.push({ name });
      }
    }
    return;
  }

  // 尝试对象形式：emits: { event1: (payload: Type) => true }
  const objectStartMatch = body.match(RE_EMITS_OBJECT_START);
  if (objectStartMatch) {
    const emitsBody = extractBracedContent(
      body,
      objectStartMatch.index! + objectStartMatch[0]!.length - 1,
    );
    if (emitsBody) {
      const eventNames = emitsBody.match(/(\w+)\s*:/g);
      if (eventNames) {
        for (const event of eventNames) {
          const name = event.replace(/[\s:]/g, '');
          info.emits.push({ name });
        }
      }
    }
    return;
  }
}

// ============================================================
// 类型映射工具函数
// ============================================================

/**
 * 将 Vue 风格的 prop 类型构造函数映射到 TypeScript 类型。
 */
function mapPropType(rawType: string): string {
  const typeMap: Record<string, string> = {
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Array: 'unknown[]',
    Object: 'Record<string, unknown>',
    Function: '(...args: unknown[]) => unknown',
    Symbol: 'symbol',
  };
  return typeMap[rawType] ?? rawType;
}

/**
 * 将字符串首字母大写。
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * 将 kebab-case 或 snake_case 文件名转换为 PascalCase。
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((part) => capitalize(part))
    .join('');
}

/**
 * 去除文件名的扩展名。
 */
function stripExtension(filename: string): string {
  const lastDot = filename.lastIndexOf('.');
  return lastDot > 0 ? filename.slice(0, lastDot) : filename;
}
