 
import { describe, it, expect } from 'vitest';
import {
  generateRenderCode,
  generateHoistedCode,
  generatePatchFlags,
} from '../../src/wasm/wasm-generator';

describe('generateRenderCode', () => {
  it('should generate render function code', () => {
    const code = generateRenderCode('<div>Hello</div>');
    expect(code).toContain('function render');
  });

  it('should generate code with prefix', () => {
    const code = generateRenderCode('<div>test</div>', {
      prefix: '// Generated by LytJS',
    });
    expect(code).toContain('// Generated by LytJS');
    expect(code).toContain('function render');
  });

  it('should generate SSR code when ssr option is true', () => {
    const code = generateRenderCode('<div>test</div>', { ssr: true } as any);
    expect(code).toBeDefined();
    expect(typeof code).toBe('string');
    expect(code.length).toBeGreaterThan(0);
  });

  it('should handle empty template', () => {
    const code = generateRenderCode('');
    expect(code).toBeDefined();
    expect(typeof code).toBe('string');
  });

  it('should generate code for complex templates', () => {
    const code = generateRenderCode('<div v-if="show"><span>{{ msg }}</span></div>');
    expect(code).toContain('function render');
  });
});

describe('generateHoistedCode', () => {
  it('should return empty string for simple template without hoists', () => {
    const code = generateHoistedCode('<div>test</div>');
    expect(code).toBe('');
  });

  it('should return hoisted code for template with static subtrees', () => {
    const code = generateHoistedCode('<div><span>static</span>{{ dynamic }}</div>');
    expect(typeof code).toBe('string');
  });

  it('should handle empty template', () => {
    const code = generateHoistedCode('');
    expect(typeof code).toBe('string');
  });
});

describe('generatePatchFlags', () => {
  it('should return patch flags for dynamic templates', () => {
    const flags = generatePatchFlags('<div>{{ msg }}</div>');
    expect(flags).toBeDefined();
    expect(typeof flags).toBe('object');
  });

  it('should return empty object for fully static templates', () => {
    const flags = generatePatchFlags('<div>static text</div>');
    expect(flags).toBeDefined();
    expect(typeof flags).toBe('object');
  });

  it('should return flags with string keys representing node paths', () => {
    const flags = generatePatchFlags('<div :class="cls">{{ msg }}</div>');
    for (const key of Object.keys(flags)) {
      expect(typeof key).toBe('string');
      expect(typeof flags[key]).toBe('number');
    }
  });

  it('should handle empty template', () => {
    const flags = generatePatchFlags('');
    expect(flags).toBeDefined();
    expect(typeof flags).toBe('object');
  });
});
