/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars, no-console, @typescript-eslint/no-require-imports */
// tests/sfc/typescript.test.ts
// Tests for TypeScript type declaration generation

import { describe, it, expect } from 'vitest';
import { parseSFC } from '../../src/sfc/parse';
import { generateComponentTypes } from '../../src/sfc/typescript';

// ============================================================
// Test SFC sources
// ============================================================

const SFC_WITH_DEFINE_COMPONENT = `<template>
  <div>{{ message }}</div>
</template>

<script>
import { defineComponent } from '@lytjs/core'

export default defineComponent({
  name: 'HelloWorld',
  props: {
    title: { type: String, required: true },
    count: { type: Number, required: false },
  },
  emits: ['update', 'change'],
  data() { return { message: 'hello' } }
})
</script>`;

const SFC_WITH_EXPORT_DEFAULT = `<template>
  <div>test</div>
</template>

<script>
export default {
  name: 'SimpleComponent',
  props: {
    label: { type: String, required: true },
    visible: { type: Boolean, required: false },
  },
  emits: ['toggle'],
}
</script>`;

const SFC_WITHOUT_PROPS = `<template>
  <div>no props</div>
</template>

<script>
export default {
  name: 'NoPropsComponent',
}
</script>`;

const SFC_WITHOUT_SCRIPT = `<template>
  <div>no script</div>
</template>`;

const SFC_WITH_SIMPLE_PROPS = `<template>
  <div>simple</div>
</template>

<script>
export default {
  name: 'SimpleProps',
  props: {
    name: String,
    age: Number,
    active: Boolean,
  },
  emits: ['click'],
}
</script>`;

const SFC_WITH_OBJECT_EMITS = `<template>
  <div>object emits</div>
</template>

<script>
export default {
  name: 'ObjectEmits',
  emits: {
    submit: (payload: string) => true,
    cancel: () => true,
  },
}
</script>`;

// ============================================================
// Tests
// ============================================================

describe('generateComponentTypes', () => {
  // ----------------------------------------------------------
  // Basic type generation
  // ----------------------------------------------------------

  it('should generate a .d.ts file with import statement', () => {
    const descriptor = parseSFC(SFC_WITH_DEFINE_COMPONENT, {
      filename: 'HelloWorld.lyt',
    });
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('import type { Component } from');
    expect(result).toContain('Auto-generated by @lytjs/compiler');
  });

  it('should generate props interface from defineComponent', () => {
    const descriptor = parseSFC(SFC_WITH_DEFINE_COMPONENT, {
      filename: 'HelloWorld.lyt',
    });
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('HelloWorldProps');
    expect(result).toContain('readonly title: string');
    expect(result).toContain('readonly count?: number');
  });

  it('should mark required props without optional marker', () => {
    const descriptor = parseSFC(SFC_WITH_DEFINE_COMPONENT);
    const result = generateComponentTypes(descriptor);

    // title is required, so no '?' suffix
    expect(result).toMatch(/readonly title: string;/);
    // count is not required, so has '?' suffix
    expect(result).toMatch(/readonly count\?: number;/);
  });

  // ----------------------------------------------------------
  // Emits type generation
  // ----------------------------------------------------------

  it('should generate emits interface from array form', () => {
    const descriptor = parseSFC(SFC_WITH_DEFINE_COMPONENT);
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('HelloWorldEmits');
    expect(result).toContain('onUpdate: (): void');
    expect(result).toContain('onChange: (): void');
  });

  it('should generate emits interface from object form', () => {
    const descriptor = parseSFC(SFC_WITH_OBJECT_EMITS);
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('ObjectEmitsEmits');
    expect(result).toContain('onSubmit');
    expect(result).toContain('onCancel');
  });

  // ----------------------------------------------------------
  // Component instance type
  // ----------------------------------------------------------

  it('should generate component instance type', () => {
    const descriptor = parseSFC(SFC_WITH_DEFINE_COMPONENT);
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('HelloWorldInstance');
    expect(result).toContain('InstanceType<Component<HelloWorldProps, HelloWorldEmits>>');
  });

  // ----------------------------------------------------------
  // Default export
  // ----------------------------------------------------------

  it('should generate default export declaration', () => {
    const descriptor = parseSFC(SFC_WITH_DEFINE_COMPONENT);
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('declare const _default:');
    expect(result).toContain('export default _default');
  });

  // ----------------------------------------------------------
  // Component name extraction
  // ----------------------------------------------------------

  it('should extract component name from script', () => {
    const descriptor = parseSFC(SFC_WITH_EXPORT_DEFAULT, {
      filename: 'SimpleComponent.lyt',
    });
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('SimpleComponentProps');
    expect(result).toContain('SimpleComponentEmits');
  });

  // ----------------------------------------------------------
  // Filename-based name fallback
  // ----------------------------------------------------------

  it('should derive component name from filename when name is not in script', () => {
    const descriptor = parseSFC(SFC_WITHOUT_PROPS, {
      filename: 'derived-name.lyt',
    });
    const result = generateComponentTypes(descriptor);

    // "NoPropsComponent" is in the script, so it should use that
    expect(result).toContain('NoPropsComponent');
  });

  it('should convert kebab-case filename to PascalCase', () => {
    const source = `<template><div>test</div></template>
<script>
export default {}
</script>`;
    const descriptor = parseSFC(source, {
      filename: 'my-component.lyt',
    });
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('MyComponent');
  });

  // ----------------------------------------------------------
  // No props / no script
  // ----------------------------------------------------------

  it('should handle component without props', () => {
    const descriptor = parseSFC(SFC_WITHOUT_PROPS);
    const result = generateComponentTypes(descriptor);

    // Should not have a Props interface
    expect(result).not.toContain('Props {');
    // Should still have InstanceType with empty props
    expect(result).toContain('InstanceType<Component<{}>>');
  });

  it('should handle component without script block', () => {
    const descriptor = parseSFC(SFC_WITHOUT_SCRIPT, {
      filename: 'no-script.lyt',
    });
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('NoScript');
    expect(result).toContain('InstanceType<Component<{}>>');
  });

  // ----------------------------------------------------------
  // Simple prop declarations
  // ----------------------------------------------------------

  it('should handle simple prop type declarations', () => {
    const descriptor = parseSFC(SFC_WITH_SIMPLE_PROPS);
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('SimplePropsProps');
    expect(result).toContain('readonly name?: string');
    expect(result).toContain('readonly age?: number');
    expect(result).toContain('readonly active?: boolean');
  });

  // ----------------------------------------------------------
  // Type mapping
  // ----------------------------------------------------------

  it('should map Vue prop types to TypeScript types', () => {
    const source = `<template><div>types</div></template>
<script>
export default {
  props: {
    str: { type: String, required: true },
    num: { type: Number, required: true },
    bool: { type: Boolean, required: true },
    arr: { type: Array, required: true },
    obj: { type: Object, required: true },
    fn: { type: Function, required: true },
  },
}
</script>`;
    const descriptor = parseSFC(source);
    const result = generateComponentTypes(descriptor);

    expect(result).toContain('readonly str: string');
    expect(result).toContain('readonly num: number');
    expect(result).toContain('readonly bool: boolean');
    expect(result).toContain('readonly arr: unknown[]');
    expect(result).toContain('readonly obj: Record<string, unknown>');
    expect(result).toContain('readonly fn: (...args: unknown[]) => unknown');
  });
});
